sonar.projectKey=otp2_fuel_trip_cost_calc
sonar.projectName=Fuel consumption and trip cost calculator

sonar.sources=src
sonar.java.binaries=target/classes

# exclude tests and JavaFX files from test coverage calculation
sonar.coverage.exclusions=**/src/test/java/**,**/HelloController.java,**/HelloApplication.java,**/Launcher.java

sonar.host.url=http://localhost:9000